on:
  release:
    types:
      - published

name: release

jobs:
  pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: Build Dependencies
        run: python -m pip install -U build

      - name: Build Package
        run: python -m build

      - name: Publish Package Distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
